# Generated by Django 2.2.3 on 2021-01-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20210125_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre del Producto'),
        ),
    ]
