# Generated by Django 2.2.3 on 2021-07-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20210126_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_caducidad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
