# Generated by Django 2.2.3 on 2021-02-16 00:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20210212_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 2, 15, 19, 35, 35, 862104), verbose_name='Fecha de compra'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.Proveedor', verbose_name='Proveedor'),
        ),
    ]
