# Generated by Django 2.2.3 on 2021-07-17 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_auto_20210716_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 23, 48, 44, 686692), verbose_name='Fecha de compra'),
        ),
    ]
