# Generated by Django 2.2.3 on 2021-01-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_auto_20201219_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del Proveedor'),
        ),
    ]
