# Generated by Django 2.2.3 on 2021-07-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_auto_20210126_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='proveedores/'),
        ),
    ]
