# Generated by Django 2.2.3 on 2020-12-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('total', models.FloatField(verbose_name='Total')),
                ('total_venta', models.FloatField(verbose_name='Total a Pagar')),
                ('productos', models.ManyToManyField(to='productos.Producto', verbose_name='Productos')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['fecha'],
            },
        ),
    ]
