# Generated by Django 2.2.3 on 2020-12-20 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_detalleventa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='Producto',
            new_name='producto',
        ),
    ]
