# Generated by Django 2.2.3 on 2021-02-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_auto_20210215_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(default='15/02/2021', verbose_name='Fecha de venta'),
        ),
    ]
