# Generated by Django 2.2.3 on 2021-02-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_auto_20210215_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default='Monday 15/02/2021 19:30:44', verbose_name='Fecha de venta'),
        ),
    ]
