# Generated by Django 2.2.3 on 2021-02-16 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_auto_20210215_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 19, 35, 35, 846480), verbose_name='Fecha de venta'),
        ),
    ]
