# Generated by Django 2.2.3 on 2021-02-16 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_auto_20210215_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 19, 37, 10, 810422), verbose_name='Fecha de venta'),
        ),
    ]
